[package]
name = "monsite"
version = "0.1.0"
authors = ["elielim <elimek2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix="2.0"
actix="2.0"
